### ISSUE TITLE
Add Line Integral Convolution Vector Visualization

### ISSUE THREAD

**Issue by Adnan-Ali-Ahmad** [nvaytet/osyris#37]
Hello,

I'd like to suggest a new feature: line integral convolution (LIC) visualization for vector fields! I've made an implementation of the feature myself on my local Osyris repo, and here's what the results look like for the sample data when visualizing the velocity vector field:
![lic](https://user-images.githubusercontent.com/60321972/138488554-33d0314b-a85e-42bf-b7a2-3d36fffa6f38.png)

Essentially, this allows us to clearly see the orientation of velocity vector field while ditching any information on magnitude and direction. We can circumvent this problem by also adding quiver arrows to the plot:
![lic_with_quiver](https://user-images.githubusercontent.com/60321972/138488238-72b2dc2e-391d-4b58-80f8-96d6c75a20c6.png)

You can see that the eddy-like structure of the velocity field at the top-center-right of the image is invisible with quiver arrows, whereas you can clearly distinguish it with the LIC. Obviously, this works better with higher resolution data, here's some examples from some of my simulations:

![SIDE_DX2_density_slice_with_lic00264](https://user-images.githubusercontent.com/60321972/138489299-17c8736b-dc12-44bc-b46c-bfdced0d523c.png)
You can see how nicely this displays shock fronts!
![sc_slices](https://user-images.githubusercontent.com/60321972/138489306-6fa333be-e044-453e-b7eb-c85b112fcf42.png)

Adding this feature is quite easy since there's already a pip module that does all the work for us ([licpy](https://pypi.org/project/lic/)). Essentially, I've simply added a new wrapper function in wrappers.py that calculates the LIC using licpy, and then it amplifies the contrast on the result and merges it with the density plot using alpha blending. This of course requires the renderer to check if the user requested the LIC before calling the wrappers in order to add the "alpha" parameter to the plots. In addition, I can't seem to get the alpha blending to work with pcolormesh, so instead I changed its wrapper function to use imshow instead. You'll find my implementation in this zip file:
[osyris_with_lic.zip](https://github.com/nvaytet/osyris/files/7400127/osyris_with_lic.zip)

**Comment by nvaytet** [comment]
I think this is a really cool idea, thanks for the suggestion.

Why don't you try to open a pull request with your implementation (you'll need to fork the repository before you can open a pull request), and we can discuss the changes there, instead of sharing via a zip file.

Cheers!
