### ISSUE TITLE
radius not updated after re-centering

### ISSUE THREAD

**Issue by tinecolman** [nvaytet/osyris#4]
The radius r and log(r) are calculated when loading the data but not updated automatically when calling re_center. Is this intended?

**Comment by nvaytet** [comment]
No, this is not intended. I'll try to find time to make a fix, or you could also look into it and make a PR if you feel like it?
I've had problems with `re_center` before and it has not been used extensively, so i'm not surprised you're having problems there.

**Comment by tinecolman** [comment]
I can look into it. Not that it is an urgent issue. Maybe the most natural is to move the calculating of r to the end of re_center.
