### ISSUE TITLE
Dataset' object has no attribute 'new_field'

### ISSUE THREAD

**Issue by ttepperg** [nvaytet/osyris#44]
Hi,

I just installed Osyris, I'm using Python 3.7.
Whenever I try to load ANY snapshot I get the following error:

Processing 144 files in ../hbd_10_gd2/output_00028
 10% : read    1875407 cells,     410354 particles
 20% : read    3662871 cells,     429341 particles
 30% : read    5496349 cells,    1252774 particles
 40% : read    7284029 cells,    1269491 particles
 50% : read    9027489 cells,    1720208 particles
 60% : read   10899849 cells,    2160275 particles
 70% : read   12687449 cells,    2177850 particles
 80% : read   14522050 cells,    3004021 particles
 90% : read   16309098 cells,    3027178 particles
Loaded: 18059049 cells, 3423247 particles.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tepper/Library/Python/3.7/lib/python/site-packages/osyris/core/dataset.py", line 66, in load
    config.additional_variables(self)
  File "/Users/tepper/.osyris/config_osyris.py", line 80, in additional_variables
    holder.new_field(name="velocity", operation="momentum/density",
AttributeError: 'Dataset' object has no attribute 'new_field'

So, as you see, the data appears to load fine but it is the Dataset class which
seems to be missing something.

Thor

**Comment by Adnan-Ali-Ahmad** [comment]
Hello Thor, it seems like your config_osyris.py file is still in version 1.
Neil suggests you try deleting it if you don't have important changes there and Osyris will create a new one.

**Comment by nvaytet** [comment]
The file should be located in a folder called something like `/home/user/.osyris`

**Comment by ttepperg** [comment]
Hi guys,

Issue resolved, thanks!

Thor
